language: generic

git:
  depth: 10

env:
  global:
  - PROG_VER=$(cat VERSION.txt)

matrix:
  include:

    - os: osx
      osx_image: xcode9.3
      env:
      - task=build
      - arch=osx
      - sourceforge_mirror=pilotfiber
      install:
      - sh -c 'cd setup/macosx && ./compilers.sh'
      script:
      - echo -en 'travis_fold:start:build'
      - sh -c 'cd setup/macosx && ./create_app_new.sh'
      - echo -en 'travis_fold:end:build'
      after_success:
      - md5 ./setup/macosx/transgui-$PROG_VER.dmg
      - shasum -a 1 ./setup/macosx/transgui-$PROG_VER.dmg
      - shasum -a 256 ./setup/macosx/transgui-$PROG_VER.dmg
      - if [ -n "$TRAVIS_TAG" ] ; then
          curl -F "file=@./setup/macosx/transgui-$PROG_VER.dmg" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ;
          curl -F "file=@./transgui" -F apikey=${virustotal} https://www.virustotal.com/vtapi/v2/file/scan ;
        else
          setup/upload_asset.sh ./setup/macosx/transgui-$PROG_VER.dmg ;
        fi
      deploy:
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./setup/macosx/transgui-$PROG_VER.dmg
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    on_failure: true
